FROM ghcr.io/centers-health/dev:3

# Install fzf
RUN git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && \
    ~/.fzf/install --all

USER root

# Install Starship
RUN curl -sS https://starship.rs/install.sh | sh -s -- --yes

# Install GH cli
RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg && \
    sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
    sudo apt-get update && \
    sudo apt-get install --no-install-recommends gh -y

# Install Stow
RUN apt-get update && \
    apt-get install --no-install-recommends stow -y

USER docker
WORKDIR /home/docker

# Copy Dotfiles
COPY --chown=docker:docker . dotfiles/

# Move wakatime.cfg to home directory
RUN mv dotfiles/.wakatime.cfg $HOME/.wakatime.cfg

# Copy over ssh keys
RUN mkdir $HOME/.ssh/ \
    && cp -r dotfiles/keypairs/* $HOME/.ssh/ \
    && find $HOME/.ssh/ -type f ! -name "*.pub" -exec chmod 600 {} + \
    && chmod 644 $HOME/.ssh/*.pub

RUN rm .bashrc

# Stow Dotfiles
WORKDIR /home/docker/dotfiles/stowables/scripts-shared/.local/bin
RUN yarn install

WORKDIR /home/docker/dotfiles
RUN stow -R --dir=stowables --target=$HOME \
    bash \
    git \
    scripts-shared \
    starship


WORKDIR /app

ARG JIRA_API_TOKEN
ARG JIRA_API_USER
ARG GITHUB_TOKEN

ENV JIRA_API_TOKEN=${JIRA_API_TOKEN} \
    JIRA_API_USER=${JIRA_API_USER} \
    GITHUB_TOKEN=${GITHUB_TOKEN}
